### ISSUE TITLE
Benchmark loss issue on 20/0417

### ISSUE THREAD

**Issue by akavkl** [z2-dev/android_device_zuk_z2_plus#74] opened 2017-04-27 14:16 UTC
***
*ISSUES ARE NOT A DISCUSSION/SUPPORT FORUM*. Comments irrelevant to the issue WILL be removed.

If this issue is to report a bug, please provide everything you can from the list below:
- ROM build version (date):
- logcat (pastebin link):
- dmesg (pastebin link):
- console-ramoops (pastebin link):
- Steps to reproduce:

**Comment by AlvaroBrey** [comment] 2017-04-27 16:07
Duplicate of #75

**Closed as completed by AlvaroBrey** 2017-04-27 16:07 UTC
Labels: duplicate
