### ISSUE TITLE
Hangs up to a hard reboot.

### ISSUE THREAD

**Issue by Cahbka1992** [z2-dev/android_device_zuk_z2_plus#141] opened 2017-09-29 08:56 UTC
The phone hangs periodically. When the screen is frozen, the screen is turned off and the indicator is dimly lit with small flashes. Until you reboot it with a long press of the power button.

**Comment by AlvaroBrey** [comment] 2017-09-29 09:45
Duplicate of #21

**Closed as completed by AlvaroBrey** 2017-09-29 09:45 UTC
Labels: duplicate
