### ISSUE TITLE
Sometimes screen light intensity goes to minimum by itself.

### ISSUE THREAD

**Issue by jtnmartinho** [z2-dev/android_device_zuk_z2_plus#28] opened 2017-02-27 11:02 UTC
Sometimes screen light intensity goes to minimum by itself. I have adaptable screen light set on.

I can't reproduce the bug, so I guess that I can't do a logcat.

**Comment by AlvaroBrey** [comment] 2017-02-27 11:07
I need a bit more of a description. What do you mean "goes to minimum by itself"? 
The way adaptable brightness works is, if there's less ambient light, the screen brightness will decrease.
Is this what's happening? Or is it decreasing when it's bright outside (which would be wrong?

Also, does it stay that way, or does it correct itself if you leave it for some seconds?

**Comment by jtnmartinho** [comment] 2017-02-27 11:15
Sometimes, when I turn the screen on, brightness setting is all the way down. I have to set it to a brighter level again. Then it stays that way until it happens again, and it happened to me 2 or 3 times. Can't tell if it happens only on the latest build, or if it happened on the earlier too.

**Comment by AlvaroBrey** [comment] 2017-02-27 11:20
So what you're saying is that the  brightness bar (slider) goes to minimum?

**Comment by jtnmartinho** [comment] 2017-02-27 12:39
Yes, brightness bar (slider) goes to minimum.

**Comment by marchi19217** [comment] 2017-02-28 12:28
Do you have a screen protector? Did you try cleaning the ambient sensor on the top of the screen?

**Comment by jtnmartinho** [comment] 2017-02-28 13:05
I do have a screen protector - transparent tempered glass. I guess that's not related. It only happened 2 or 3 times, always when I turn the screen on. Also, the brightness slider goes all the way down to minimum, it should stay were I set it, it does not move when the phone automatically sets the screen brightness accordingly to the surrounding light conditions.

**Comment by marchi19217** [comment] 2017-03-03 06:23
Screen protectors, especially glass ones can block the ambient sensor and cause the issues you are experiencing. I suggest removing your screen protector.

I installed the latest build to test the bug and cannot reproduce it so far

**Comment by jtnmartinho** [comment] 2017-03-03 12:41
Thanks for your help, but I'am sorry to disagree. I can't see what the screen protector has to do with this specific issue. I'm not able to reproduced it, it happened 2 or 3 times for no apparent reason - and it didn't happened to me again, but it's unpredictable. When I turn the screen on, the screen brightness was very low and the slider was on the minimum by itself. Even if I have something blocking the sensor it doesn't affect the brightness slider position.

I have Power Toggles app installed, and a widget were I can set, among other things, the brightness between minimum, medium, maximum and auto. Maybe this issue has to do with this app, sorry for not remember this sooner. However, it's not me changing the brightness toggle by mistake, and even if I set it to the minimum, I've tried it now, it doesn't set the brightness slider all the way down.

**Comment by AlvaroBrey** [comment] 2017-03-03 12:52
@jtnmartinho I can only suggest trying to get logs if it happens again, but since this is the only report I've got about this issue, I'm inclined to think it's got something to do with that third party app.

I'm leaving this issue open for now to see if we get more info. If after a while we have no more reports or info I'll close it.

**Comment by jtnmartinho** [comment] 2017-03-03 17:47
[alogcat.2017-03-03-17-42-52+0000.txt](https://github.com/ontherunvaro/android_device_zuk_z2_plus/files/817483/alogcat.2017-03-03-17-42-52.0000.txt)

It happened again: around 17h39m. I've installed (root)alogcat app after, so I don't know if it will be useful. 

I'm on today's build, and my phone was charging connected to my laptop.

**Comment by AlvaroBrey** [comment] 2017-03-04 11:30
I've read through that log and found nothing of interest. The only thing that stands out is this:
```
I/art     ( 3671): Method exceeds compiler instruction limit: 22422 in void com.koo.lightmanager.LMNotificationListenerService.onNotificationPosted(android.service.notification.StatusBarNotification)
```
Which is related to LED Settings app. I don't think that's the cause though, because it happened AFTER you installed alogcat.

As no useful info is provided, I shall close this issue in a weeks time unless:

- You remove Power Toggles, and still get the same issue
- Some other user reports this bug without having Power Toggles installed.

_P.S.: why would you install Led Manager if we don't have RGB led?_

**Comment by jtnmartinho** [comment] 2017-03-04 15:53
Since I'm the only one with this bug, and it's not relevant, close the issue whenever you want. Thanks for looking trough the log.

I started using led manager since I got not led notification on missed calls - led works fine on sms, charging, etc. I will test led for missing calls again.

Thanks for your patience and work. Cheers! : )

**Comment by jtnmartinho** [comment] 2017-03-04 16:18
Uninstalled Power Toggles and Light Manager. I can live without the toggles widget, but I need missing calls led notifications. I've tried without light manager and I can't get the led to work on missing calls. Maybe something to do with another app.

**Comment by AlvaroBrey** [comment] 2017-03-04 22:09
I've updated #7 to identify it as a verified bug. I'm also closing this issue. Thanks for the help!

**Closed as completed by AlvaroBrey** 2017-03-04 22:09 UTC
Labels: bug-not verified, needs logs
