### ISSUE TITLE
SIP missing in Contacts

### ISSUE THREAD

**Issue by MikhailRyazanov** [z2-dev/android_device_zuk_z2_plus#104] opened 2017-06-21 08:54 UTC
In Android Contacts, "Add new contact" and "Edit contact" do not show the SIP address field (supposedly, it should appear between "IM" and "Website").

Interestingly enough, importing a vCard with an X-SIP field works, such that the imported SIP address can be seen when viewing the contact (and can be called), but even then it does not show up in "Edit contact".

**Comment by AlvaroBrey** [comment] 2017-06-21 09:01
The SIP field appears for me if I tap the "More fields" link at the bottom of the screen. It's not between IM and Website as you say, but above Email.

**Comment by MikhailRyazanov** [comment] 2017-06-21 09:40
Did a fresh install and still do not see it anywhere:

<img src="https://user-images.githubusercontent.com/12854133/27377310-d83e4254-5631-11e7-8b87-1f613e81caea.png" width="100"> <img src="https://user-images.githubusercontent.com/12854133/27377317-db5782de-5631-11e7-8078-ca61e3c44c78.png" width="100">

Tried immediately after install, then after adding a SIP account, then tried to import a vCard — same results. Do I need to do something specific?

**Comment by AlvaroBrey** [comment] 2017-06-21 09:56
Do you have GApps installed? If so, which package?

**Comment by AlvaroBrey** [comment] 2017-06-21 09:58
Oh, actually I just realized. The `SIP` field only appears if you save the contact to an account, not when saving it to the phone.

It looks like it's intentional. Either way it's definitely upstream, not a problem with my builds.

**Comment by MikhailRyazanov** [comment] 2017-06-22 01:03
Interesting. Would you report it there or should I? (Then please tell me where exactly the problem is.)

By "save the contact to an account" do you mean a Google account? I do not want to use it.

(Just noticed that there is actually one place where I could see the SIP field: if I tap "Set up my profile" in Contacts, it _is_ present where it should be. But after filling and saving, it becomes hidden! The only way to edit it is to erase that contact completely and fill everything anew.)

**Comment by AlvaroBrey** [comment] 2017-06-22 08:10
Yes, I meant Google account, I guess any other accounts that can save contacts would work as well.

About reporting it, you may report it to the BUGBASH issue tracker at jira.lineageos.org (only open on weekends), or try to get some dev to notice you in ##lineageos at irc.freenode.net.

**Comment by AlvaroBrey** [comment] 2017-07-05 08:55
@MikhailRyazanov I see you opened the issue and promptly got it closed as "not from official device". I've got a spare official device around here, I'll try to reproduce the bug and open the issue with it.

**Comment by MikhailRyazanov** [comment] 2017-07-06 20:48
Thank you, this will be great! (I was thinking about finding somebody who can report it "officially"...)
Let me know if you need any help from my side.

**Comment by AlvaroBrey** [comment] 2017-07-22 12:17
https://jira.lineageos.org/browse/BUGBASH-824

**Comment by AlvaroBrey** [comment] 2017-07-29 10:04
This was fixed upstream (https://review.lineageos.org/#/c/182162/) and it's fine on the latest release.
Cheers!

**Closed as completed by AlvaroBrey** 2017-07-29 10:04 UTC
Labels: upstream
