### ISSUE TITLE
Cellular data is on by default

### ISSUE THREAD

**Issue by SistemaKrasho** [z2-dev/android_device_zuk_z2_plus#71] opened 2017-04-19 15:51 UTC
After a fresh install, cellular data is active by default. It's quite the inconvenience since carriers may charge for simply enabling cellular data, like mine does.

Please consider changing this behaviour.

A workaround for users: remove all your SIM cards before flashing then disable cell data in settings before putting them back in.

**Comment by AlvaroBrey** [comment] 2017-04-20 14:40
Probably upstream, I will try to investigate some more.

**Comment by wajeehuzkhan** [comment] 2017-04-30 14:06
I can confirm this 
but this issue isnt exclusive to LOS but present in every custom rom i have tried

**Comment by AlvaroBrey** [comment] 2017-05-01 16:14
Yes, I believe this is a design choice rather than a bug, since it's present on other phones on android 7.x as well. Closing for now.

**Closed as completed by AlvaroBrey** 2017-05-01 16:14 UTC
Labels: upstream
