### ISSUE TITLE
Cellular data is off But the fact is not

### ISSUE THREAD

**Issue by 508279079** [z2-dev/android_device_zuk_z2_plus#33] opened 2017-03-07 05:39 UTC
Turn off the cellular data,it also has internet access.(关掉数据网络，仍然可以上网）

**Comment by AlvaroBrey** [comment] 2017-03-07 09:08
It should take a couple of seconds for data to be turned off after you click the switch.
Apart from that I can't reproduce your bug. You sure you don't have wifi or something?

**Comment by 508279079** [comment] 2017-03-07 09:53
Yes, I sure.

**Comment by AlvaroBrey** [comment] 2017-03-07 09:59
Alright, changing status to bug-unverified. Needs logs though. If no more info or more reports come in the next week, I'm closing this.

**Comment by 508279079** [comment] 2017-03-07 11:55
Maybe because I modified the system file. Wait me to flash the rom and test again.

**Closed as completed** 2017-03-08 15:48 UTC
Labels: invalid

**Comment by 508279079** [comment] 2017-08-17 15:06
The 20170811 version still has this problem, and I know how to reproduce it.
In this situation: Mobile data is on, 4G LTE Mode (Search in Settings) is on, using cmnet APN.
Reproduce: Turn on flight mode, then turn off flight mode. Turn off the mobile data, you will find that you can still go online.
