### ISSUE TITLE
Vídeo recording crashes

### ISSUE THREAD

**Issue by eirisdg** [z2-dev/android_device_zuk_z2_plus#25] opened 2017-02-21 23:21 UTC
Vídeo recording crashes in any resolution

**Comment by AlvaroBrey** [comment] 2017-02-22 00:06
Can't reproduce your issue, video recording is fine on my end. What camera app are you using?

**Comment by luci-11** [comment] 2017-02-22 11:45
the problem is a little bit wider (i compared my phone to the one of another guy on 17th build and we have the same behaviour, hope you can reproduce it too):

stock camera:
1) after first boot/reboot --> video recording is working fine
2) as soon as you make a video over 30 sec with preinstalled camera, at 30sec the preview becomes blocked the every video you make remains stuck at first frame until reboot

another camera app:
in any case i had some random crashes also with another app with different video lenght.. trying to catch all problems in several logs.  (p.s. after crash in secondary app, stock camera can record again_ but after 30 sec it stops again)

**Comment by AlvaroBrey** [comment] 2017-02-22 12:06
@luci-11 I can't reproduce your issue either :\ Video recording is working perfectly for me in stock Camera app.

**Comment by luci-11** [comment] 2017-02-22 12:17
:( i really don't know.. we get the same behaviour at each reboot...
are you on clean install? i come from 11th version with wipes except system.. later i'll try with system wipe too :)   _ EDIT: the other guy comes directly from 17th version_ so this is not the problem
attached the two logs if useful:  (30 is the block after 30 sec and the other is the following stuck video)
[videostuck30_stock.txt](https://github.com/ontherunvaro/android_device_zuk_z2_plus/files/793305/videostuck30_stock.txt)
[videostuck_stock.txt](https://github.com/ontherunvaro/android_device_zuk_z2_plus/files/793306/videostuck_stock.txt)
i also have the log about the crash but as it is another app i don't think it's useful for you

**Comment by AlvaroBrey** [comment] 2017-02-22 12:21
@luci-11 I contacted @eirisdg and he told me the camera isn't crashing anymore, I think we should move your bug to a different issue and close this one as invalid.
Anyway, bug reports must ALWAYS come from a clean flash. In fact, in the install instructions there's a step to wipe system, cache & dalvik.
Edit: system, dalvik and *cache*, not data

**Closed as completed by AlvaroBrey** 2017-02-22 12:21 UTC
Labels: invalid

**Comment by luci-11** [comment] 2017-02-22 12:27
my fault, i did system and not data as in istructions .. in any case i'll investigate more :)

**Comment by AlvaroBrey** [comment] 2017-02-22 12:28
sorry, meant system, dalvik and cache, *not* data!
